AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  myapi-endpoint

  API to handle Log tracking of a user

Parameters:
  ENVIRONMENT:
    Type: String
    Description: AWS Environment where code is being executed (AWS_SAM_LOCAL or AWS)
    Default: 'AWS_SAM_LOCAL'

  DYNAMODBDEVURI:
    Type: String
    Description: AWS local DynamoDB instance URI (will only be used if AWSENVNAME is AWS_SAM_LOCAL)
    Default: 'http://docker.for.mac.host.internal:8000'

Globals:
  Function:
    Timeout: 60

Resources:
  UserLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_log/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          ENVIRONMENT: !Ref ENVIRONMENT
          DYNAMODBDEVURI: !Ref DYNAMODBDEVURI
      Events:
        CreateAPI:
          Type: Api
          Properties:
            Path: /user_log
            Method: post
            RestApiId:
              Ref: UserLogApi
  UserLogApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: Prod
        Name: UserLogApi
        Auth:
          ApiKeyRequired: false
          UsagePlan:
            CreateUsagePlan: PER_API
            Quota:
              Limit: 50
              Period: DAY
            Throttle:
              RateLimit: 5
  myDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserLog
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S          
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE          
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 1
Outputs:
  UserLogApi:
    Description: "API Gateway endpoint URL for Prod stage for LogUser function"
    Value: !Sub "https://${UserLogApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user_log/"
